### PR TITLE
fix ssr type signature

### PR DESCRIPTION
**Pull request by iacore**
The test code I used:

```
declare var initSsr: (content?: string, mimeType?: string) => any;

initSsr()
initSsr("hi")
initSsr("hi", "there")
```

### CODE REVIEW

**Comment by WebReflection** [comment]
This doesn't work as per contract https://github.com/WebReflection/uhtml/blob/main/esm/dom/dom-parser.js#L74 or better, I have a default value for the `mimeType` and I don't want accidental pass of `null` or something that would shadow that ... but more over, what is this trying to solve? what is still broken and why is that an issue?

**Comment by WebReflection** [comment]
I see ... I've put the `?` where it shouldn't be 🤦‍♂️

**Comment by WebReflection** [comment]
OK, this is in with latest and it also fallsback to the correct `mimeType` as opposite of passing potentially `null` or falsy values (not undefined).

**Comment by iacore** [comment]
[default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) is basically `param ?? defaultParam`.

My patch is fine type-wise.

```
❯ cat d.ts
declare var initSsr: (content?: string, mimeType?: string) => any;

initSsr()
initSsr("hi")
initSsr("hi", "there")
initSsr("hi", null)
initSsr("hi", false)

❯ deno check d.ts
Check file:///tmp/d.ts
error: TS2345 [ERROR]: Argument of type 'null' is not assignable to parameter of type 'string | undefined'.
initSsr("hi", null)
              ~~~~
    at file:///tmp/d.ts:6:15

TS2345 [ERROR]: Argument of type 'boolean' is not assignable to parameter of type 'string'.
initSsr("hi", false)
              ~~~~~
    at file:///tmp/d.ts:7:15

Found 2 errors.
```

**Comment by WebReflection** [comment]
I don't use deno or TS so that guard still defaults to the right expected thing despite tools checking around ... this should be OK now and I don't want to spend extra time on this. Thanks for the hint though, it's in.

**Pull request closed without merging**
